version: '3.1'

services:
  jupyter:
    build: jupyter
    volumes:
      - ./jupyter/notebooks:/home/jovyan/work
    ports:
      - 8888:8888
  db:
    build: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: retailrocket

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  jupyter:
